ports:
  - port: 8080
    onOpen: open-preview
tasks:
  - command: code complete/src/main/java/hello/HelloController.java
  - before: cd complete
    init: ./gradlew clean build
    command: ./gradlew bootRun
github:
  prebuilds:
      pullRequestsFromForks: true
